#!/usr/bin/env python3
"""Build the ARR appendix from the ICLR manuscript.

The ARR limit is 8 content pages; Limitations, Ethics, References and Appendix
are excluded from it. The ICLR source is 35 single-column pages, and almost all
of that length is evidence a reviewer asked for -- per-family tables, null
calibrations, the four failed rollout-gate attempts, the judge validation. None
of it should be cut. So the conversion is not a compression problem: the body is
rewritten tight in cot_faith_arr.tex by hand, and everything else moves here,
verbatim, where there is no page limit.

Verbatim matters. Retyping 190k characters of measured numbers into an appendix
is exactly how a manuscript and its artifacts drift apart, and this repo's audit
exists because that already happened once. So this script COPIES rather than
rewrites, and applies only the mechanical transforms two-column layout forces:

  1. sections demote to subsections (the appendix's own \\section headers group
     them), so cross-references keep resolving against the same \\label
  2. table/figure -> table*/figure* so wide floats span both columns
  3. the abstract, title block and bibliography are dropped -- the ARR file
     supplies its own

Anything else that differs between the two documents is a bug in this script,
and `--check` asserts the invariant that makes that detectable: every \\label in
the source survives into the appendix, so no \\ref in the rewritten body can
dangle at build time and be discovered by a reader instead.
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "cot_faith_iclr.tex"
DEST = ROOT / "arr_appendix.tex"

HEADER = r"""% ============================================================
% GENERATED by scripts/build_arr_appendix.py -- do not edit by hand.
% Source: cot_faith_iclr.tex (the full-length version).
% Regenerate:  python3 scripts/build_arr_appendix.py
%
% This is the evidence for the 8-page body in cot_faith_arr.tex. ARR excludes
% the appendix from the 8-page limit but caps the whole PDF at 20 pages, so
% this is a selection: the sections it leaves out are named in the deferred
% list it generates, no \label the body \ref's into is ever dropped, and every
% number carried over is the source's own.
% ============================================================
"""


def transform(src: str) -> str:
    # --- take the body only -------------------------------------------------
    start = src.index(r"\end{abstract}") + len(r"\end{abstract}")
    end = src.index(r"\bibliographystyle")
    body = src[start:end]

    # Drop the Conclusion: it restates the body, and the body is what the
    # 8 pages are for. Keeping it here would leave two conclusions in one PDF.
    m = re.search(r"\n\\section\{Conclusion\}", body)
    if m:
        body = body[:m.start()]

    # --- demote the heading levels -----------------------------------------
    # \section -> \subsection etc. The appendix supplies its own \section
    # grouping, and demoting rather than deleting keeps every \label attached
    # to a real sectioning unit so \ref and hyperref still resolve.
    body = re.sub(r"\\subsection\{", r"\\subsubsection{", body)
    body = re.sub(r"\\section\{", r"\\subsection{", body)

    # --- widen the floats ---------------------------------------------------
    # In two columns an 13-column table silently overflows into the gutter.
    # Starred floats span the page; they can only sit at the top, which is
    # fine for an appendix.
    body = re.sub(r"\\begin\{table\}(\[[^\]]*\])?", r"\\begin{table*}[t]", body)
    body = re.sub(r"\\end\{table\}", r"\\end{table*}", body)
    body = re.sub(r"\\begin\{figure\}(\[[^\]]*\])?", r"\\begin{figure*}[t]", body)
    body = re.sub(r"\\end\{figure\}", r"\\end{figure*}", body)

    # --- let long \texttt paths break across lines --------------------------
    # \texttt is unbreakable, and a 60-character artifact path in a 3.1-inch
    # column runs clear off the page: the first ARR build produced a 347pt
    # overfull box on
    #   ours_{lora-r8,...,data-50B}_edit_13family_RETRAIN.json
    # which is text a reader physically cannot see. Single-column at 6.5in
    # absorbed these, so they appear only in the two-column conversion.
    #
    # \allowbreak after each separator gives TeX a legal breakpoint without
    # inserting a hyphen, so no break can be misread as part of a filename.
    # Applied only inside \texttt{...} -- the separators mean nothing in prose.
    #
    # The hyphen is in the list because HF repo ids are the one long \texttt
    # span that carries none of the others: \texttt{openvla-7b-finetuned-
    # libero-spatial} ran 10.9pt past the column, and breakable() had already
    # run on it and found nothing to break. A hyphen is a legal breakpoint that
    # stays with the line above, so the break cannot be read as an added
    # character the way a hyphenation would be.
    def breakable(m):
        inner = m.group(1)
        if len(inner) < 24:          # short spans fit; leave them alone
            return m.group(0)
        inner = re.sub(r"(/|\\_|\{|,|-)", r"\1\\allowbreak{}", inner)
        return r"\texttt{" + inner + "}"

    body = re.sub(r"\\texttt\{([^{}]*(?:\{[^{}]*\}[^{}]*)*)\}", breakable, body)

    # --- shrink the over-wide tabulars to fit -------------------------------
    # Two separate overflows, one fix.
    #
    # (a) \begin{center}\small\begin{tabular} blocks written inline are not
    #     floats, so the table*/figure* rewrite above misses them and they keep
    #     their natural width -- 193pt past a 3.1in column in the first build.
    #     They cannot become table*: they sit mid-argument, and a float would
    #     drift to a page where the sentence introducing it no longer points at
    #     anything.
    # (b) table* spans the full 6.5in page, but a 13-column table from a
    #     single-column source can exceed even that.
    #
    # \fitwidth (defined in cot_faith_arr.tex) measures the box and scales only
    # if it overflows, so tables that already fit keep their natural size
    # rather than being blown up to the margin.
    def fit(target):
        def sub(m):
            inner = m.group(0)
            if r"\fitwidth" in inner:
                return inner
            return (inner.replace(r"\begin{tabular}",
                                  r"\fitwidth{" + target + r"}{\begin{tabular}",
                                  1)
                         .replace(r"\end{tabular}", r"\end{tabular}}", 1))
        return sub

    body = re.sub(r"\\begin\{center\}.*?\\end\{center\}",
                  fit(r"\columnwidth"), body, flags=re.S)
    body = re.sub(r"\\begin\{table\*\}.*?\\end\{table\*\}",
                  fit(r"\textwidth"), body, flags=re.S)

    # --- anonymize -----------------------------------------------------------
    # ARR is double-blind. The repo name is the sharpest leak here: it is
    # searchable on GitHub and resolves straight to the authors, and it appears
    # inside vendored source paths where it reads as incidental. The compute
    # platform's name is the milder one, but it is named in provenance
    # sentences ("released with its Bolt task id") that identify the
    # infrastructure an author has access to.
    #
    # Substituted rather than deleted: the provenance sentences are load-bearing
    # -- they are what makes each run attributable to a specific job -- so the
    # ids stay and only the platform's name is generalized. Restore at
    # camera-ready by re-running this script against a --final flag, which does
    # not exist yet because there is nothing to restore into.
    for pat, sub in (
        (r"\bsharpguard/", "anonrepo/"),
        (r"\bsharpguard\b", "anonrepo"),
        (r"\bBolt task id", "compute-platform task id"),
        (r"\bbolt task id", "compute-platform task id"),
        (r"\bbolt \\texttt", r"compute-platform \\texttt"),
        (r"\bICLR 2026\b", "the original venue"),
    ):
        body = re.sub(pat, sub, body)

    # --- drop the floats the body promoted ----------------------------------
    # See PROMOTED below. Removing the float leaves its surrounding prose
    # intact: the source discusses each one in running text that still reads
    # correctly with the exhibit a few pages earlier in the body, and every
    # \ref to it resolves to the body's copy.
    for lab in PROMOTED:
        env = "table" if lab.startswith("tab:") else "figure"
        pat = (r"\\begin\{" + env + r"\*?\}(?:\[[^\]]*\])?"
               r"(?:(?!\\begin\{" + env + r").)*?"
               r"\\label\{" + re.escape(lab) + r"\}"
               r".*?\\end\{" + env + r"\*?\}\s*")
        body, n = re.subn(pat, "", body, flags=re.S)
        if n != 1:
            raise SystemExit(f"[arr] promoted float {lab}: removed {n}, "
                             f"expected 1 -- the body and the appendix would "
                             f"both define it")

    # --- drop the floats deferred for space ---------------------------------
    # See DEFERRED_FLOATS below. Unlike PROMOTED these have no copy anywhere in
    # the submission, so the dangling-\ref check below is what makes this safe:
    # a float label cannot be re-homed onto the deferred list the way a section
    # label can (\label outside a float picks up the section counter, so the
    # \ref would print a section number and read as a figure that does not
    # exist), so every reference to one has to be rewritten by hand first.
    for lab, _ in DEFERRED_FLOATS:
        env = "table" if lab.startswith("tab:") else "figure"
        pat = (r"\\begin\{" + env + r"\*?\}(?:\[[^\]]*\])?"
               r"(?:(?!\\begin\{" + env + r").)*?"
               r"\\label\{" + re.escape(lab) + r"\}"
               r".*?\\end\{" + env + r"\*?\}\s*")
        body, n = re.subn(pat, "", body, flags=re.S)
        if n != 1:
            raise SystemExit(f"[arr] deferred float {lab}: removed {n}, "
                             f"expected 1 -- either it is already gone or the "
                             f"regex no longer matches its environment")

    # --- drop the pointers into floats that are no longer here --------------
    # A deferred float leaves at most a sentence behind, and rewriting that
    # sentence in cot_faith_iclr.tex would be wrong: the figure IS there, one
    # paragraph away, so the pointer is correct in the document this is copied
    # from and only stale here. Dropped rather than unpointed, because
    # "the heatmap in the full-length manuscript visualizes the same table" is a
    # sentence that spends a line telling the reader about a figure they cannot
    # see. Every entry is asserted to occur exactly once, so a source edit that
    # rewords the sentence fails here instead of leaving a dangling \ref for the
    # guard below to catch by its label.
    for lit, why in DROPPED_POINTERS:
        if body.count(lit) != 1:
            raise SystemExit(f"[arr] dropped pointer {lit[:40]!r}: occurs "
                             f"{body.count(lit)} times, expected 1 ({why})")
        body = body.replace(lit, "")

    # --- rewrite the sentences that are true only of the source document ------
    # See REWORDED below. Same exactly-once assert as the pointers, and it runs
    # before defer()/unpoint() so a replacement may carry a \ref like any other
    # sentence: if it points into deferred material the guards downstream catch
    # it, rather than this loop having to know what survives.
    for lit, new, why in REWORDED:
        if body.count(lit) != 1:
            raise SystemExit(f"[arr] reworded {lit[:40]!r}: occurs "
                             f"{body.count(lit)} times, expected 1 ({why})")
        body = body.replace(lit, new)

    # --- move a float to where the appendix has room for it -----------------
    # See HOISTED below. This changes a float's POSITION and not one byte of
    # its content: the environment is cut and re-inserted verbatim.
    for lab, anchor in HOISTED:
        env = "table" if lab.startswith("tab:") else "figure"
        pat = (r"\\begin\{" + env + r"\*?\}(?:\[[^\]]*\])?"
               r"(?:(?!\\begin\{" + env + r").)*?"
               r"\\label\{" + re.escape(lab) + r"\}"
               r".*?\\end\{" + env + r"\*?\}\s*")
        m = re.search(pat, body, flags=re.S)
        if m is None:
            raise SystemExit(f"[arr] hoisted float {lab}: not found")
        if body.count(anchor) != 1:
            raise SystemExit(f"[arr] hoisted float {lab}: its anchor occurs "
                             f"{body.count(anchor)} times, expected 1")
        at = body.index(anchor)
        if at > m.start():
            raise SystemExit(f"[arr] hoisted float {lab}: the anchor is AFTER "
                             f"the float, so this moves it later rather than "
                             f"earlier and cannot free a page")
        blk = m.group(0)
        body = body[:m.start()] + body[m.end():]
        at = body.index(anchor)
        body = body[:at] + blk + body[at:]

    # --- fit the submission budget ------------------------------------------
    body, deferred_labels, deferred_entries = defer(body)
    deferred_labels |= {lab for lab, _ in DEFERRED_FLOATS}
    body, empty_heads = drop_empty_heads(body)
    deferred_labels |= {l for _, secs in empty_heads for l in secs}
    deferred_entries += empty_heads

    # --- namespace every surviving label ------------------------------------
    # The body was written by hand and reuses the source's names for the
    # sections and equations it restates: sec:intro, eq:delta, eq:faith,
    # eq:fdir and three more were defined in BOTH files. LaTeX resolves a
    # duplicate to whichever it read last -- the appendix -- so body text
    # saying "Eq. 1" was pointing thirty pages away, and it emits a Warning,
    # not an Error, so four clean builds shipped with it.
    #
    # Prefixing the appendix's copies fixes it in one place. Refs INSIDE the
    # appendix are rewritten to match, so its internal cross-references still
    # land on its own copy; refs in the body keep pointing at the body's.
    body_src = DEST.parent / "cot_faith_arr.tex"
    arr = body_src.read_text() if body_src.exists() else ""
    body_labels = labels(arr)

    # A deferred section the BODY also has under its own name needs no re-homing
    # and must not get one: sec:intro and sec:related are defined in both files,
    # so a re-homed copy in the list below would define them twice and \ref
    # would resolve to whichever LaTeX read last -- silently, since a duplicate
    # \label is a warning. Those refs belong on the body's own sections anyway.
    deferred_entries = [(t, [l for l in secs if l not in body_labels])
                        for t, secs in deferred_entries]

    # A deferred section must not be one something still points at. \ref to a
    # missing label prints "??" and pdflatex only warns, so this is asserted
    # here rather than left to be found in the PDF by a reader.
    #
    # Section labels are the exception, and they are re-homed rather than left
    # to dangle: deferred_list() re-attaches each one to the entry that names
    # its section, so a sentence saying "see \S~\ref{sec:f2_calib}" lands on the
    # list, which tells the reader that section is in the released full-length
    # version. A float label cannot be treated that way -- \label outside a
    # float picks up the section counter, so \ref{tab:x} would print a section
    # number and read as a table that does not exist -- so those still fail.
    # LaTeX comments are excluded, and that distinction is load-bearing rather
    # than cosmetic: both manuscripts carry preamble comments explaining what a
    # float is and why its placement was tuned, and those sentences cite it by
    # \ref like the prose does. A \ref TeX never typesets cannot print "??", so
    # counting one would make deferring a documented float impossible.
    pointed_at = set(re.findall(r"\\(?:ref|autoref|eqref|Cref|cref)\{([^}]*)\}",
                                uncommented(body) + uncommented(arr)))
    rehomed = {l for _, secs in deferred_entries for l in secs}
    dangling = sorted((deferred_labels - rehomed - body_labels) & pointed_at)
    if dangling:
        raise SystemExit(
            f"[arr] FAIL: {len(dangling)} deferred label(s) are still "
            f"referenced, so \\ref would print '??': {dangling}")

    # Re-homing keeps \ref from printing "??", but the number it then prints is
    # the deferred LIST's, and nineteen sentences in the appendix read "see
    # Section A.6" where A.6 is the list of what A.6 is not. So the pointer is
    # spent rather than redirected: the sentence names the document the section
    # is in. Nothing else may still point at a re-homed label afterwards --
    # including the hand-written body, which this script cannot rewrite, so a
    # ref there has to be fixed by hand and this is what says so.
    body = unpoint(body, rehomed)
    # A plural head with two deferred refs under it ("Sections~\ref{a}
    # and~\ref{b}") is rewritten one ref at a time above, so it printed the
    # document's name twice: "the central negative result of Sections~the
    # full-length manuscript and~the full-length manuscript". Collapse the pair,
    # then assert no doubled phrase survives anywhere -- the collapse is a
    # literal rewrite and the guard is what makes the next shape of this defect
    # fail the build instead of printing.
    body = re.sub(r"Sections~" + re.escape(UNPOINT)
                  + r"\s+and~?\s*" + re.escape(UNPOINT),
                  "the sections deferred to " + UNPOINT, body)
    doubled = re.findall(re.escape(UNPOINT) + r"[^.]{0,20}?"
                         + re.escape(UNPOINT), body)
    if doubled:
        raise SystemExit(
            f"[arr] FAIL: {len(doubled)} unpointed reference(s) print the "
            f"document name twice in one phrase: {doubled}")
    circular = sorted(rehomed & set(re.findall(
        r"\\(?:ref|autoref|eqref|Cref|cref)\{([^}]*)\}",
        uncommented(body) + uncommented(arr))))
    if circular:
        raise SystemExit(
            f"[arr] FAIL: {len(circular)} reference(s) resolve to the list of "
            f"deferred sections, which sends the reader in a circle: "
            f"{circular}")

    if body_src.exists():
        for lab in sorted(labels(body) & body_labels):
            body = body.replace(r"\label{" + lab + "}",
                                r"\label{app:" + lab + "}")
            body = re.sub(r"(\\(?:ref|autoref|eqref|Cref|cref)\{)"
                          + re.escape(lab) + r"\}",
                          r"\1app:" + lab + "}", body)

    out = (HEADER + "\n\\section{Evidence for the body}\n"
           "\\label{sec:appendix}\n" + NOTE + body.strip() + "\n"
           + deferred_list(deferred_entries))

    # Every \ref the appendix prints must land on a \label one of the two files
    # defines. The guards above cover the labels this script DROPS; this one
    # covers the labels it never had. The deferred list is prose written here
    # rather than copied, and its first draft cited two labels by the names they
    # have after namespacing -- which they do not have, since only labels the
    # body also defines are prefixed. Both printed as "??" on the last page of
    # the submission, in the one paragraph whose whole job is to tell a reader
    # where the missing sections are.
    unresolved = sorted(
        set(re.findall(r"\\(?:ref|autoref|eqref|Cref|cref)\{([^}]*)\}",
                       uncommented(out)))
        - labels(out) - body_labels)
    if unresolved:
        raise SystemExit(
            f"[arr] FAIL: {len(unresolved)} reference(s) in the appendix "
            f"resolve to no label in either file, so they print '??': "
            f"{unresolved}")

    return out


# Sections not reproduced in the submitted PDF. See defer(); a leading "*"
# keeps the floats inside the span and drops only its prose.
#
# ARR excludes the appendix from the 8-page body limit, but a submission is
# still a document someone has to read, and the full-length manuscript makes
# this one 54 pages. The cap we set is 20, so what ships is a SELECTION.
# Two properties make that safe to do mechanically rather than by hand:
#
#   * nothing is rewritten. Every line here is byte-identical to
#     cot_faith_iclr.tex, which ships in the release and is the document
#     scripts/verify_paper_numbers.py audits, so deferred text is one file
#     away rather than gone. The appendix says so, by name, at the end.
#   * no cross-reference may dangle. transform() fails if the body or the
#     surviving appendix still points at a label inside a deferred span.
#
# What stays is what the body's claims rest on: how the benchmark is built,
# the per-family numbers, the calibration floors that make the score
# readable, and the disclosures. What goes is the long-form narrative a
# reader can follow in the release: the four rollout-gate failures, the
# limitation enumeration, and the discussion that restates the body.
DEFERRED = (
    "Introduction",
    "*Related work",
    # The body defines the score, in the same two display equations under the
    # same names (\S2, eq:delta and eq:faith), and its "Edit families"
    # paragraph carries this section's null-control validation whole: the
    # identity control scoring $0$ on 11/11, paraphrase_null judged
    # meaning-preserving at 0.975, bbox_jitter_null at 1.000. So the copy here
    # was the definition a reader had already read three pages earlier, printed
    # a second time with its equations renumbered -- half a column spent on
    # nothing, in a document whose page cap is the reason the deferred list
    # below exists at all.
    "Faithfulness Score",
    "Per-token normalization",
    "Attention noise, decomposed.",
    "The bucket ordering is an artifact",
    "*The gate also fails on our own checkpoint",
    "The rollout gate: four failures",
    "The gate passes, and both corrections",
    "The decode defect is on the rollout path",
    "Norm-stats provenance",
    "*The blocker on that ablation is not compute",
    "Is the floor itself confounded",
    "*All eleven calibrated models",
    "Ancillary: prompt-format ablation",
    "Threshold and metric sensitivity.",
    "*What is missing.",
    r"$\mathcal{F}_{\text{dir}}$, unlike",
    "O4 (observation, not a controlled finding)",
    "F1: Attention on CoT is a floor",
    "F2: Causal effect requires",
    "F2 calibrated",
    "F3: Attention distribution does not predict",
    # The body's own "What the magnitude score counts" section carries
    # this one's argument, its table and its numbers, so the prose here
    # is a second copy. Its figure used to be the reason for the "*": fig12
    # existed nowhere else. It is now in DEFERRED_FLOATS, with its numbers
    # written into that entry, so the "*" no longer keeps anything -- it is
    # left in place because removing it would change nothing and asserting
    # that is cheaper than re-deriving it at the next edit.
    "*F6: magnitude-based edit scoring inverts the model ordering",
    "Attention-as-failure AUROC (P3): specified",
    # The body argues the paraphrase floor at length (\S3-\S4 and
    # tab:floors) and this section is its supporting detail, including the
    # out-of-CoT walk-through that used to be deferred separately as a child
    # of it. The floats stay: the leaderboard caption and the taxonomy's
    # coverage sentence both point at tab:calibration.
    "*Paraphrase-null: models are sensitive to surface tokens",
    # "Do the edit families do what their names say" was deferred here. It is
    # the judge protocol, and both floors the paper reports -- the paraphrase
    # null and the cross_task_swap ceiling -- are certified meaning-preserving
    # by that judge, in the body's own tab:floors caption. Deferring it left
    # the certification behind every headline number in neither half of the
    # submission, which is a worse trade than the third of a column it costs.
    "*F7: P2 on a second architecture family",
    "*P3, re-run in-domain",
    "*Limitation (v), measured",
)

NOTE = r"""
This appendix carries the evidence the eight-page body cites, copied from the
full-length manuscript rather than rewritten for it, so no number here is
retyped. It is a selection: the submitted PDF is capped at $20$ pages, and the
sections it does not reproduce are named in \S\ref{sec:deferred}, which says
where to read them. Where a sentence would have cited one of those sections it
names that document instead of a number, and where one pointed at a dropped
float the pointer is dropped too, so every cross-reference in these pages lands
on something the reader can turn to.

"""

LEVELS = {"subsection": 1, "subsubsection": 2, "paragraph": 3}
HEAD = r"\\(subsection|subsubsection|paragraph)\{"
FLOAT = re.compile(r"\\begin\{(table|figure)\*\}.*?\\end\{\1\*\}\s*", re.S)

# Filled by defer(); read by main()'s no-label-may-be-lost guard, which has to
# tell a deliberate deferral from a section that fell out by accident.
DEFERRED_LABELS = set()


def defer(body: str):
    """Drop each DEFERRED span.

    Returns (body, every label dropped, [(title, [section labels dropped])]).
    """
    dropped, entries = set(), []
    for entry in DEFERRED:
        floats_stay = entry.startswith("*")
        title = entry.lstrip("*")
        m = re.search(HEAD + re.escape(title), body)
        if not m:
            raise SystemExit(f"[arr] FAIL: deferred section {title!r} is not "
                             f"in the source under that name")
        # The span ends at the next heading that is not a child of this one.
        level = LEVELS[m.group(1)]
        end = len(body)
        for nxt in re.finditer(HEAD, body[m.end():]):
            if LEVELS[nxt.group(1)] <= level:
                end = m.end() + nxt.start()
                break
        span = body[m.start():end]
        keep = "".join(f.group(0) for f in FLOAT.finditer(span)) \
            if floats_stay else ""
        gone = labels(span) - labels(keep)
        dropped |= gone
        entries.append((heading_title(span),
                        sorted(l for l in gone if l.startswith("sec:"))))
        body = body[:m.start()] + keep + body[end:]
    DEFERRED_LABELS.update(dropped)
    return body, dropped, entries


# Both starred and unstarred, unlike FLOAT: defer() only ever has to recognize
# the full-width floats, but a heading can be emptied down to a single-column
# one just as easily.
ANY_FLOAT = re.compile(r"\\begin\{(table|figure)\*?\}.*?\\end\{\1\*?\}\s*", re.S)


def drop_empty_heads(body: str):
    """Delete every heading whose prose was deferred out from under it.

    defer() drops spans, and a parent heading whose children all went with them
    is left printing a numbered title with nothing under it. `A.5 Discussion
    and limitations` shipped that way for four builds, with three \\ref pointing
    into it, two of them naming numbered items that are only in the deferred
    text. Floats inside the span are content the submission keeps, and they
    carry their own captions, so they outlive the heading they sat under.

    Returns (body, [(title, [section labels dropped])]) in defer()'s shape, so
    the caller can re-home the labels onto the deferred list like any other.
    One heading is dropped per pass and the scan restarts, because dropping a
    child can be what empties its parent.
    """
    entries = []
    while True:
        for m in re.finditer(HEAD, body):
            level = LEVELS[m.group(1)]
            end = len(body)
            for nxt in re.finditer(HEAD, body[m.end():]):
                if LEVELS[nxt.group(1)] <= level:
                    end = m.end() + nxt.start()
                    break
            span = body[m.start():end]
            title, after = braced(span)
            floats = "".join(f.group(0) for f in ANY_FLOAT.finditer(span))
            rest = re.sub(r"\\label\{[^}]*\}", "",
                          ANY_FLOAT.sub("", uncommented(span[after:])))
            if rest.strip():
                continue
            entries.append(
                (title, sorted(l for l in labels(span) - labels(floats)
                               if l.startswith("sec:"))))
            body = body[:m.start()] + floats + body[end:]
            break
        else:
            return body, entries


UNPOINT = "the full-length manuscript"


def unpoint(body: str, rehomed: set) -> str:
    """Rewrite every \\ref into a deferred section as prose.

    The label is the wrong thing to point at once its section is gone (see the
    caller), so the reference is replaced by the name of the document that has
    it. An optional `Section~`/`Appendix~`/`\\S~` in front is swallowed, since
    "Section the full-length manuscript" is not English.
    """
    if not rehomed:
        return body
    pat = re.compile(r"(?:(?:Section|Appendix|\\S)~?\s*)?"
                     r"\\(?:ref|autoref|Cref|cref)\{(?:"
                     + "|".join(re.escape(l) for l in sorted(rehomed)) + r")\}")

    def sub(m):
        # Capitalized when it opens a sentence: one of these follows a period
        # inside \textbf{...}, so the closing brace counts as a full stop too.
        head = body[:m.start()].rstrip()
        upper = head.endswith((".", "!", "?", "}"))
        return (UNPOINT[0].upper() if upper else UNPOINT[0]) + UNPOINT[1:]

    return pat.sub(sub, body)


def heading_title(span: str) -> str:
    """The braced argument of the heading `span` opens with."""
    return braced(span)[0]


def braced(span: str):
    """(braced argument of the heading `span` opens with, index just past it).

    Brace-counted rather than matched by regex: two of these titles carry
    $\\mathcal{F}_{\\text{dir}}$, which nests two deep, and a regex that
    stops at the first unbalanced brace silently returns a truncated title
    -- which would print a mangled entry in the deferred list.
    """
    i = span.index("{", span.index("\\"))
    depth = 0
    for j in range(i, len(span)):
        depth += {"{": 1, "}": -1}.get(span[j], 0)
        if depth == 0:
            return span[i + 1:j], j + 1
    raise SystemExit(f"[arr] FAIL: unbalanced heading: {span[:60]!r}")



def deferred_list(entries) -> str:
    # Run together rather than itemized. 27 one-line \items spend a third of a
    # column on bullets and inter-item leading, and this list is a pointer
    # rather than something a reader works down; the \labels that were re-homed
    # onto the items ride along in the same order, so a \ref still lands here.
    items = "; ".join(t.strip().rstrip(".")
                      + "".join(r"\label{" + l + "}" for l in secs)
                      for t, secs in entries)
    return (r"""
\subsection{Sections deferred to the full-length manuscript}
\label{sec:deferred}
The submitted PDF is capped at $20$ pages, so these sections of the full-length
manuscript are not reproduced above. They are in the released source
(\texttt{cot\_faith\_iclr.tex}), the document the audit script checks claim by
claim and the one every line above was copied from, and they are named here so
that a reader can tell what exists from what was cut. Where the pages above
draw on one of them the sentence names that document rather than a section
number, so no reference above resolves to this list:
""" + items + ".\n" + floats_note())


def floats_note() -> str:
    # Floats are named separately from the sections, because a deferred float
    # sits inside a section that DID survive: a reader who meets
    # \S\ref{sec:taxonomy} with no figure in it should be told the figure exists
    # rather than assume the section was printed whole.
    if not DEFERRED_FLOATS:
        return ""
    return ("\nDeferred with them, from sections that are otherwise reproduced "
            "in full: " + "; ".join(d for _, d in DEFERRED_FLOATS) + ".\n")


ANON_FORBIDDEN = ("sharpguard", "ICLR 2026")

# Floats the ARR body now carries itself. They must be REMOVED here: a \label
# defined in both files makes the number LaTeX prints unpredictable, and the
# duplicate is a warning rather than an error, so it ships silently.
# The body is the definition; the appendix cites it by \ref like any other.
# fig:paths is also the anti-duplication half of the rollout split: the pose
# panels are drawn by the body float and the appendix keeps only fig:frames, so
# the same capture is not drawn twice in one submission. The split runs this way
# round rather than the other because the body's claim -- an edit reaches the
# actuator and keeps the arm moving -- is legible at print size in a two-panel
# line plot and is not legible in eighteen thumbnails, and because the strip is
# 261pt of artwork against the pose panels' 124pt on a body at its page limit.
PROMOTED = ("tab:directional", "fig:dissociation", "fig:paths")

# Floats deferred for space, as (label, how the deferred list names it). These
# have NO copy in the submission at all, unlike PROMOTED.
#
# fig:taxonomy is the one entry, and it is the cheapest full page in the
# document: 387pt of artwork plus a ten-line full-width caption, on a page
# budget that the per-task decomposition section put over 20. What it draws
# that the prose does not is one real (original, edited) excerpt per family;
# what it draws that the prose DOES is every family name, tier and judged
# meaning-preserved rate, all of which survive in \S sec:taxonomy and
# \S sec:judge_edits. So the deferral costs the reader the illustration and no
# fact. It stays in the full-length manuscript, where it is Figure 6.
DEFERRED_FLOATS = (
    ("fig:taxonomy",
     r"the taxonomy figure, ``The edit taxonomy, with the real text each "
     r"family rewrites'': one panel per family with a real "
     r"generator-output excerpt of the span it rewrote, from "
     r"\texttt{figures/\allowbreak{}fig1\_\allowbreak{}task\_"
     r"\allowbreak{}examples.pdf} in the release"),
    # The next three are cut for the same reason and by the same standard the
    # taxonomy figure was: each draws numbers the surviving prose prints, and
    # none of the three was pointed at by a single \ref in either document.
    #
    # tab:crossfamily is the sharpest case. Its four rows are four rows of
    # tab:calibration -- the same runs, as its own section says -- plus one
    # subtraction, floor - F-bar, which the section states in words for each
    # row. So the appendix printed the second architecture family's
    # calibration twice, three pages apart, and the reference in the
    # leaderboard caption now names the block of tab:calibration that holds it.
    ("tab:crossfamily",
     r"``P2 on the DeepThinkVLA family (F7)'', whose four rows are four rows "
     r"of the two-sided calibration table for the same runs, plus the "
     r"$\bar{\mathcal{F}}_{\text{diff}}$ subtraction the cross-family "
     r"section states in words for each"),
    ("fig:cross_corpus",
     r"``Cross-corpus attention profile (F5)'': the four-corpus attention "
     r"bar chart, every bar and error bar of which is printed as a "
     r"mean$\pm$std in the paragraph above it"),
    ("fig:cross_corpus_edit",
     r"``Cross-corpus causal-edit response (F5)'': the eight-bar "
     r"\emph{direction\_flip}/\emph{gripper\_flip} chart, every bar of which "
     r"is printed with its own $N$ in the paragraph above it, including the "
     r"two protocol disclosures from its caption"),
    # And the fifth, which is the plainest duplicate in the submission: its own
    # caption opens "This is Table 6", and the 88 cells it colours are the 88
    # cells of the leaderboard three pages earlier, printed there with the
    # error bars the heatmap cannot show. The colour ramp is the only thing it
    # adds, and it adds it to a table the paper explicitly says is not a
    # ranking. The generator, its 13-family coverage and the group split all
    # stay under audit against cot_faith_iclr.tex, where the figure prints.
    ("fig:edit_heatmap",
     r"``The same magnitude scores as a heatmap, all 13 families'', whose 88 "
     r"coloured cells are the 88 cells of the leaderboard table, without its "
     r"error bars"),
    # The sixth, and the only one whose numbers are not printed elsewhere in
    # these pages, so they are printed HERE: the entry carries the panel's
    # whole content and defers the drawing of it. It is the last float cut and
    # the reason is arithmetic -- with it in, the submission set 21 pages
    # against a cap of 20, and the alternative cuts were a measurement or the
    # only picture of a rollout in the paper. Its own caption already records
    # that two of its three panels were removed for redrawing tab:directional
    # digit for digit; what is deferred now is the third.
    ("fig:directional",
     r"``The differential leaderboard'': $\mathcal{F}_{\text{diff}} = "
     r"\mathcal{F}(f) - \mathcal{F}(\text{paraphrase\_null})$ for "
     r"\emph{ours-no-CoT}, the one model whose floor ($0.19$) is low enough "
     r"for the differential to be readable, over all $12$ non-reference "
     r"families. The numbers are here, the drawing is in the release: the "
     r"whole floor-to-ceiling band is $0.07$ wide, from "
     r"\emph{selfsplice\_control} at $-0.193$ (the identity null, minus the "
     r"floor by construction) and \emph{bbox\_jitter\_null} at $-0.147$ up to "
     r"the ceiling, the random instruction substitution "
     r"\emph{instr\_random\_sub} at $+0.070$; $8$ of the $12$ families sit "
     r"below their own floor, the four that clear it do so by "
     r"${\leq}0.081$, and \emph{direction\_flip}'s $+0.081$ is \emph{above} "
     r"that ceiling: a meaning-changing edit moves this model no further "
     r"than a random instruction does"),
)

# Sentences that exist only to point at a float this appendix does not print,
# as (literal, which float it pointed at). See the loop in transform().
DROPPED_POINTERS = (
    (r" Fig.~\ref{fig:edit_heatmap} visualizes the same table as a heatmap.",
     "fig:edit_heatmap, deferred above"),
)

# Sentences whose CONTENT is true of the full-length manuscript and false of
# this appendix, as (literal, replacement, why). Distinct from DROPPED_POINTERS,
# which deletes; and from unpoint(), which only swaps a \ref for a document
# name. These are rewritten because deleting them would remove something the
# reader needs, and rewriting them in cot_faith_iclr.tex would make that
# document wrong.
#
# The one entry is the Analysis opener. In the source it promises to answer five
# questions and then answers them, four of the five in sections deferred here.
# So verbatim it advertises F1--F3 and O4 twelve pages from any argument for
# them, and points at the direction-aware section as "then", when here that
# section is a table with no prose. What the appendix actually adds to those
# four is what the replacement says: the evidence the eight-page body cites.
REWORDED = (
    (r"We now use CoT-Faith to answer five questions about manipulation "
     r"CoT-VLAs: three (F1--F3) that admit controlled comparisons under our "
     r"benchmark, one (O4) that we treat as an uncontrolled observation "
     r"because two axes are confounded, and one (F5) on cross-corpus transfer "
     r"at $N{=}100$. Section~\ref{sec:directional} then re-examines all of "
     r"them under a direction-aware scoring rule, which reverses the "
     r"leaderboard ordering.",
     r"The body answers five questions about manipulation CoT-VLAs with "
     r"CoT-Faith: F1--F3 under controlled comparisons, O4 as an uncontrolled "
     r"observation because two axes are confounded, and F5 on cross-corpus "
     r"transfer at $N{=}100$. It argues four of the five in place "
     r"(\S\ref{sec:deferred}); this section adds F5 in full, the per-task "
     r"decomposition behind the below-floor result, and the judge validation "
     r"of the edit generators all five are scored with.",
     "F1--F3 and O4 are deferred, so the source's 'we now answer' opener "
     "promises four arguments this document does not print"),
)

# Floats moved earlier in the appendix, as (label, the literal string to put it
# in front of). Position only: the environment is re-inserted byte-identical.
#
# Why this is needed at all: a float's page is decided by where it is DECLARED,
# and [t] floats can only move forward. fig:paths is declared in the full-length
# manuscript inside the rollout-gate discussion, nearly all of which is deferred
# here, so in the appendix it arrives with no text after it and drains onto a
# page of its own -- a 21st page holding one figure. Declaring it in front of the
# per-task table puts it in the queue where there is room, and the appendix is a
# selection rather than a reading order, so nothing about the figure or the text
# it sits between changes. The guard in transform() refuses an anchor that would
# move a float LATER, which is the way this would silently stop working.
#
# It is fig:frames rather than fig:paths for the reason PROMOTED gives: the two
# floats are declared seven lines apart inside the same deferred discussion, so
# whichever one the appendix keeps inherits the same empty page after it.
HOISTED = (
    ("fig:frames", r"\subsubsection{Per-task decomposition"),
)


def labels(text: str) -> set:
    return set(re.findall(r"\\label\{([^}]*)\}", text))


def uncommented(text: str) -> str:
    # Drop LaTeX comments: an unescaped % to end of line. \% is a printed
    # percent sign and starts nothing, which matters here because the appendix
    # quotes parse-failure rates as 10.2\%.
    return re.sub(r"(?<!\\)%.*", "", text)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the generated file is current and complete")
    args = ap.parse_args()

    src = SRC.read_text()
    out = transform(src)

    # The invariant worth asserting: no label may be lost. A dropped label
    # turns every \ref to it into a '??' in the PDF, which is the kind of
    # defect that ships because nobody reads the appendix of their own paper.
    src_labels = labels(src)
    out_labels = labels(out)
    # A label the body also defines survives here under an app: prefix rather
    # than being lost -- see the namespacing pass in transform(). Count it as
    # present, or the guard reports a rename as a deletion.
    out_labels |= {l[4:] for l in out_labels if l.startswith("app:")}
    # The title/abstract region and the Conclusion are intentionally dropped.
    dropped = {l for l in src_labels - out_labels}
    expected_drops = ({"sec:conclusion"} | set(PROMOTED) | DEFERRED_LABELS
                      | {lab for lab, _ in DEFERRED_FLOATS})
    unexpected = dropped - expected_drops
    if unexpected:
        print(f"[arr] FAIL: {len(unexpected)} label(s) lost: "
              f"{sorted(unexpected)}", file=sys.stderr)
        return 1

    # Double-blind is a desk-reject condition, so it is asserted rather than
    # inspected. A leak that survives to the PDF is not recoverable after
    # submission.
    leaked = [s for s in ANON_FORBIDDEN if s.lower() in out.lower()]
    if leaked:
        print(f"[arr] FAIL: deanonymizing string(s) in the appendix: {leaked}",
              file=sys.stderr)
        return 1

    if args.check:
        if not DEST.exists():
            print(f"[arr] FAIL: {DEST.name} does not exist", file=sys.stderr)
            return 1
        if DEST.read_text() != out:
            print(f"[arr] FAIL: {DEST.name} is stale; regenerate it",
                  file=sys.stderr)
            return 1
        print(f"[arr] ok: {DEST.name} is current "
              f"({len(out_labels)} labels, {len(out):,} chars)")
        return 0

    DEST.write_text(out)
    print(f"[arr] wrote {DEST.name}: {len(out):,} chars, "
          f"{len(out_labels)} labels carried over")
    return 0


if __name__ == "__main__":
    sys.exit(main())
