#!/usr/bin/env python3
"""Build the ARR appendix from the ICLR manuscript.

The ARR limit is 8 content pages; Limitations, Ethics, References and Appendix
are excluded from it. The ICLR source is 35 single-column pages, and almost all
of that length is evidence a reviewer asked for -- per-family tables, null
calibrations, the four failed rollout-gate attempts, the judge validation. None
of it should be cut. So the conversion is not a compression problem: the body is
rewritten tight in cot_faith_arr.tex by hand, and everything else moves here,
verbatim, where there is no page limit.

Verbatim matters. Retyping 190k characters of measured numbers into an appendix
is exactly how a manuscript and its artifacts drift apart, and this repo's audit
exists because that already happened once. So this script COPIES rather than
rewrites, and applies only the mechanical transforms two-column layout forces:

  1. sections demote to subsections (the appendix's own \\section headers group
     them), so cross-references keep resolving against the same \\label
  2. table/figure -> table*/figure* so wide floats span both columns
  3. the abstract, title block and bibliography are dropped -- the ARR file
     supplies its own

Anything else that differs between the two documents is a bug in this script,
and `--check` asserts the invariant that makes that detectable: every \\label in
the source survives into the appendix, so no \\ref in the rewritten body can
dangle at build time and be discovered by a reader instead.
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "cot_faith_iclr.tex"
DEST = ROOT / "arr_appendix.tex"

HEADER = r"""% ============================================================
% GENERATED by scripts/build_arr_appendix.py -- do not edit by hand.
% Source: cot_faith_iclr.tex (the full-length version).
% Regenerate:  python3 scripts/build_arr_appendix.py
%
% This is the unabridged evidence for the 8-page body in cot_faith_arr.tex.
% ARR excludes the appendix from the page limit, so nothing is cut here; the
% body cites into this file by \ref, and every \label in the source survives.
% ============================================================
"""


def transform(src: str) -> str:
    # --- take the body only -------------------------------------------------
    start = src.index(r"\end{abstract}") + len(r"\end{abstract}")
    end = src.index(r"\bibliographystyle")
    body = src[start:end]

    # Drop the Conclusion: it restates the body, and the body is what the
    # 8 pages are for. Keeping it here would leave two conclusions in one PDF.
    m = re.search(r"\n\\section\{Conclusion\}", body)
    if m:
        body = body[:m.start()]

    # --- demote the heading levels -----------------------------------------
    # \section -> \subsection etc. The appendix supplies its own \section
    # grouping, and demoting rather than deleting keeps every \label attached
    # to a real sectioning unit so \ref and hyperref still resolve.
    body = re.sub(r"\\subsection\{", r"\\subsubsection{", body)
    body = re.sub(r"\\section\{", r"\\subsection{", body)

    # --- widen the floats ---------------------------------------------------
    # In two columns an 13-column table silently overflows into the gutter.
    # Starred floats span the page; they can only sit at the top, which is
    # fine for an appendix.
    body = re.sub(r"\\begin\{table\}(\[[^\]]*\])?", r"\\begin{table*}[t]", body)
    body = re.sub(r"\\end\{table\}", r"\\end{table*}", body)
    body = re.sub(r"\\begin\{figure\}(\[[^\]]*\])?", r"\\begin{figure*}[t]", body)
    body = re.sub(r"\\end\{figure\}", r"\\end{figure*}", body)

    # --- let long \texttt paths break across lines --------------------------
    # \texttt is unbreakable, and a 60-character artifact path in a 3.1-inch
    # column runs clear off the page: the first ARR build produced a 347pt
    # overfull box on
    #   ours_{lora-r8,...,data-50B}_edit_13family_RETRAIN.json
    # which is text a reader physically cannot see. Single-column at 6.5in
    # absorbed these, so they appear only in the two-column conversion.
    #
    # \allowbreak after each separator gives TeX a legal breakpoint without
    # inserting a hyphen, so no break can be misread as part of a filename.
    # Applied only inside \texttt{...} -- the separators mean nothing in prose.
    def breakable(m):
        inner = m.group(1)
        if len(inner) < 24:          # short spans fit; leave them alone
            return m.group(0)
        inner = re.sub(r"(/|\\_|\{|,)", r"\1\\allowbreak{}", inner)
        return r"\texttt{" + inner + "}"

    body = re.sub(r"\\texttt\{([^{}]*(?:\{[^{}]*\}[^{}]*)*)\}", breakable, body)

    # --- shrink the over-wide tabulars to fit -------------------------------
    # Two separate overflows, one fix.
    #
    # (a) \begin{center}\small\begin{tabular} blocks written inline are not
    #     floats, so the table*/figure* rewrite above misses them and they keep
    #     their natural width -- 193pt past a 3.1in column in the first build.
    #     They cannot become table*: they sit mid-argument, and a float would
    #     drift to a page where the sentence introducing it no longer points at
    #     anything.
    # (b) table* spans the full 6.5in page, but a 13-column table from a
    #     single-column source can exceed even that.
    #
    # \fitwidth (defined in cot_faith_arr.tex) measures the box and scales only
    # if it overflows, so tables that already fit keep their natural size
    # rather than being blown up to the margin.
    def fit(target):
        def sub(m):
            inner = m.group(0)
            if r"\fitwidth" in inner:
                return inner
            return (inner.replace(r"\begin{tabular}",
                                  r"\fitwidth{" + target + r"}{\begin{tabular}",
                                  1)
                         .replace(r"\end{tabular}", r"\end{tabular}}", 1))
        return sub

    body = re.sub(r"\\begin\{center\}.*?\\end\{center\}",
                  fit(r"\columnwidth"), body, flags=re.S)
    body = re.sub(r"\\begin\{table\*\}.*?\\end\{table\*\}",
                  fit(r"\textwidth"), body, flags=re.S)

    # --- anonymize -----------------------------------------------------------
    # ARR is double-blind. The repo name is the sharpest leak here: it is
    # searchable on GitHub and resolves straight to the authors, and it appears
    # inside vendored source paths where it reads as incidental. The compute
    # platform's name is the milder one, but it is named in provenance
    # sentences ("released with its Bolt task id") that identify the
    # infrastructure an author has access to.
    #
    # Substituted rather than deleted: the provenance sentences are load-bearing
    # -- they are what makes each run attributable to a specific job -- so the
    # ids stay and only the platform's name is generalized. Restore at
    # camera-ready by re-running this script against a --final flag, which does
    # not exist yet because there is nothing to restore into.
    for pat, sub in (
        (r"\bsharpguard/", "anonrepo/"),
        (r"\bsharpguard\b", "anonrepo"),
        (r"\bBolt task id", "compute-platform task id"),
        (r"\bbolt task id", "compute-platform task id"),
        (r"\bbolt \\texttt", r"compute-platform \\texttt"),
        (r"\bICLR 2026\b", "the original venue"),
    ):
        body = re.sub(pat, sub, body)

    return (HEADER + "\n\\section{Full-length manuscript}\n"
            "\\label{sec:appendix}\n" + body.strip() + "\n")


ANON_FORBIDDEN = ("sharpguard", "ICLR 2026")


def labels(text: str) -> set:
    return set(re.findall(r"\\label\{([^}]*)\}", text))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the generated file is current and complete")
    args = ap.parse_args()

    src = SRC.read_text()
    out = transform(src)

    # The invariant worth asserting: no label may be lost. A dropped label
    # turns every \ref to it into a '??' in the PDF, which is the kind of
    # defect that ships because nobody reads the appendix of their own paper.
    src_labels = labels(src)
    out_labels = labels(out)
    # The title/abstract region and the Conclusion are intentionally dropped.
    dropped = {l for l in src_labels - out_labels}
    expected_drops = {"sec:conclusion"}
    unexpected = dropped - expected_drops
    if unexpected:
        print(f"[arr] FAIL: {len(unexpected)} label(s) lost: "
              f"{sorted(unexpected)}", file=sys.stderr)
        return 1

    # Double-blind is a desk-reject condition, so it is asserted rather than
    # inspected. A leak that survives to the PDF is not recoverable after
    # submission.
    leaked = [s for s in ANON_FORBIDDEN if s.lower() in out.lower()]
    if leaked:
        print(f"[arr] FAIL: deanonymizing string(s) in the appendix: {leaked}",
              file=sys.stderr)
        return 1

    if args.check:
        if not DEST.exists():
            print(f"[arr] FAIL: {DEST.name} does not exist", file=sys.stderr)
            return 1
        if DEST.read_text() != out:
            print(f"[arr] FAIL: {DEST.name} is stale; regenerate it",
                  file=sys.stderr)
            return 1
        print(f"[arr] ok: {DEST.name} is current "
              f"({len(out_labels)} labels, {len(out):,} chars)")
        return 0

    DEST.write_text(out)
    print(f"[arr] wrote {DEST.name}: {len(out):,} chars, "
          f"{len(out_labels)} labels carried over")
    return 0


if __name__ == "__main__":
    sys.exit(main())
